openapi: 3.1.0
info:
  title: 산업안전 AI 어시스턴트 API
  version: v0.2.0
  summary: 산업안전 지식 베이스에 대한 질의응답 API
  description: 사용자의 질문을 받아 내부 지식 베이스(answers.json)에서 TF-IDF 기반으로 가장 관련성 높은 답변을 검색하여 반환합니다.

paths:
  /search:
    get:
      summary: 지식 베이스 검색
      description: 사용자의 자연어 질문으로 가장 관련성 높은 산업안전 규정 정보를 검색합니다.
      operationId: searchKnowledgeBase
      parameters:
        - name: q
          in: query
          required: true
          description: 검색할 사용자 질문 (예: 작업발판 관련 법령 보여줘)
          schema:
            type: string
      responses:
        '200':
          description: 검색 성공. 유사도 높은 순서로 정렬된 답변 목록을 반환합니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
        '404':
          description: 검색 결과가 없을 경우
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    SearchResult:
      type: object
      properties:
        rank:
          type: integer
          description: 추천 순위
          example: 1
        similarity_score:
          type: number
          format: float
          description: 질문과의 유사도 점수 (0.0 ~ 1.0)
          example: 0.42
        question:
          type: string
          description: 매칭된 지식 베이스의 핵심 질문
          example: "비계 작업 시 작업발판의 폭은 얼마 이상이어야 하나요?"
        context:
          type: array
          items:
            type: string
          description: 해당 규정의 적용 상황
          example: ["비계 설치 작업을 감독할 때", "비계 작업발판의 규격 및 설치 상태를 점검할 때"]
        # --- [핵심 수정] legal_basis를 단일 객체에서 객체의 배열로 변경 ---
        legal_basis:
          type: array
          items:
            $ref: '#/components/schemas/LegalBasis'
        # --- 수정 완료 ---
        practical_point:
          type: string
          description: 현장 실무 포인트
          example: "비계 작업발판을 설치할 때에는 안전한 작업 공간 확보를 위해 폭을 최소 40cm 이상으로 유지해야 합니다..."

    # --- [핵심 수정] LegalBasis 스키마 정의 ---
    LegalBasis:
      type: object
      properties:
        law_name:
          type: string
          example: "산업안전보건기준에 관한 규칙"
        article:
          type: string
          example: "제206조 (비계 등의 작업발판)"
    # --- 수정 완료 ---

    Error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "해당 질문에 대한 정보를 찾을 수 없습니다."